services:
  vault:
    container_name: vault-dev
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=root_token_for_development
    command: server -dev -dev-listen-address=0.0.0.0:8200
    volumes:
      - ../../infra/secrets/vault/config/development:/vault/config
      - ../../infra/secrets/vault/data/development:/vault/data

  vault-service:
    volumes:
      - ../../apps/rest-backend/services/vault-service/src:/app/apps/rest-backend/services/vault-service/src
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VAULT_ADDR=http://vault-dev:8200
      - VAULT_TOKEN=root_token_for_development
      - LOG_LEVEL=debug

  user-service:
    volumes:
      - ../../apps/rest-backend/services/user-service/src:/app/apps/rest-backend/services/user-service/src
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://user:password@postgres:5432/ecommerce
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis

  rest-frontend:
    volumes:
      - ../../apps/rest-frontend/src:/app/apps/rest-frontend/src
      - ../../packages/ui:/app/packages/ui
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VAULT_SERVICE_URL=http://vault-service:3010
      - USER_SERVICE_URL=http://user-service:3001
      - ORDER_SERVICE_URL=http://order-service:3002
      - PAYMENT_SERVICE_URL=http://payment-service:3003
      - PRODUCT_SERVICE_URL=http://product-service:3004
      - GATEWAY_URL=http://gateway:3000
    depends_on:
      - vault-service
      - user-service
      # - order-service
      # - payment-service
      # - product-service
      # - gateway
    networks:
      - monitoring
      - backend

  postgres:
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecommerce

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "kazunoriosaki@gmail.com"
  #     PGADMIN_DEFAULT_PASSWORD: "password"
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     - postgres

  # redis-commander:
  #   image: rediscommander/redis-commander
  #   environment:
  #     - REDIS_HOSTS=redis:redis:6379
  #   ports:
  #     - "8081:8081"
  #   depends_on:
  #     - redis

  # prometheus:
  #   ports:
  #     - "9090:9090"

  # grafana:
  #   ports:
  #     - "3002:3000"
