services:
  backend:
    container_name: backend
    build:
      context: ../
      dockerfile: ./apps/backend/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - backend
      - monitoring

  frontend:
    container_name: frontend
    build:
      context: ../
      dockerfile: ./apps/frontend/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - monitoring
      - backend

  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   networks:
  #     - backend

  # prometheus:
  #   profiles: ["monitoring"]
  #   image: prom/prometheus
  #   volumes:
  #     - ../infra/monitoring/prometheus:/etc/prometheus
  #     - prometheus_data:/prometheus
  #   ports:
  #     - "9090:9090"
  #   command:
  #     - "--config.file=/etc/prometheus/prometheus.yml"
  #     - "--storage.tsdb.path=/prometheus"
  #   networks:
  #     - monitoring

  # grafana:
  #   profiles: ["monitoring"]
  #   image: grafana/grafana
  #   depends_on:
  #     - prometheus
  #   ports:
  #     - "3002:3000"
  #   volumes:
  #     - grafana_data:/var/lib/grafana
  #     - ../infra/monitoring/grafana/provisioning:/etc/grafana/provisioning
  #   networks:
  #     - monitoring

volumes:
  postgres_data:
  # redis_data:
  # prometheus_data:
  # grafana_data:

networks:
  backend:
    driver: bridge
  monitoring:
    driver: bridge
  frontend:
    driver: bridge
