FROM node:18-alpine

WORKDIR /app

# 必要なパッケージをインストール
RUN apk add --no-cache git openssh-client && \
  npm install -g corepack@latest && \
  corepack enable && \
  corepack prepare pnpm@latest --activate

# 開発用のエントリーポイントをコピー
COPY ./docker/entrypoints/entrypoint-dev.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/entrypoint-dev.sh

ENTRYPOINT ["entrypoint-dev.sh"]
CMD ["pnpm", "run", "--filter", "user-service", "start:dev"]
