FROM node:20-alpine3.20

WORKDIR /app

# 必要なパッケージをインストール
RUN apk add --no-cache git openssh-client openssl3 && \
  npm install -g corepack@latest && \
  corepack enable && \
  corepack prepare pnpm@10.6.4 --activate

# turbo.json をコピー
COPY turbo.json ./

# ワークスペース定義とルートの package.json をコピー
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./

# 各パッケージ/アプリをコピー
COPY packages /app/packages
COPY apps /app/apps

# 依存関係をインストール
RUN pnpm install --frozen-lockfile

# 依存関係のビルド
RUN pnpm exec turbo run build --filter @portfolio-2025/prisma-schemas && \
  pnpm exec turbo run build --filter @portfolio-2025/user-service...

# プロジェクト全体のソースコードをコピー
COPY . .


# 依存関係のビルド
RUN echo "=== Building prisma-schemas (direct) ===" && \
  cd /app/packages/prisma-schemas && \
  pnpm run build
RUN echo "=== Building shared (direct) ===" && \
  cd /app/packages/shared && \
  pnpm run build

# 開発用のエントリーポイントをコピー
COPY ./docker/entrypoints/entrypoint-dev.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/entrypoint-dev.sh

ENTRYPOINT ["entrypoint-dev.sh"]
CMD ["pnpm", "run", "--filter", "user-service", "start:dev"]
