global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "backend"
    metrics_path: "/v1/sys/metrics"
    params:
      format: ["prometheus"]
    static_configs:
      - targets: ["vault:8080"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
