FROM node:18-alpine

WORKDIR /app

# 必要なパッケージをインストール
RUN apk add --no-cache git openssh-client && \
  npm install -g corepack@latest && \
  corepack enable && \
  corepack prepare pnpm@latest --activate

# 依存関係ファイルのコピー
COPY pnpm-*.* ./
COPY package.json turbo.json ./
COPY packages/ui/package.json ./packages/ui/
COPY packages/eslint-config/package.json ./packages/eslint-config/
COPY packages/typescript-config/package.json ./packages/typescript-config/
COPY apps/rest-frontend/package.json ./apps/rest-frontend/

# 依存関係をインストール
RUN pnpm install --frozen-lockfile

# 開発サーバーを起動
CMD ["pnpm", "run", "--filter", "rest-frontend", "dev"]
